### ISSUE TITLE
Crashes on setting whitelist

### ISSUE THREAD

**Issue by sapphonie** [sapphonie/TFTruer#7]
Ugh

**Comment by sapphonie** [comment]
```
(gdb) bt
--
2 | #0  0xe8f304e2 in __SourceHook_FHCls_ConCommandDispatchfalse::Func(CCommand const&) () from /home/container/tf/addons/sourcemod/bin/sourcemod.2.tf2.so
3 | #1  0xddd003dd in ForwardCommand (this=0xdde483c0 <g_Plugin>, args=...,
4 | pCmd=0xf67d2e00 <sv_pure>)
5 | at /home/runner/work/TFTruer/TFTruer/TFTrue.cpp:644
6 | #2  _ZN11CTournament13Pure_CallbackEP10ConCommandRK8CCommand (
7 | pCmd=0xf67d2e00 <sv_pure>, args=...)
8 | at /home/runner/work/TFTruer/TFTruer/tournament.cpp:504
9 | #3  0xf655efe2 in Cmd_ExecuteCommand(CCommand const&, cmd_source_t, int) ()
10 | from /home/container/bin/engine_srv.so
11 | #4  0xf655f0e2 in Cbuf_ExecuteCommand(CCommand const&, cmd_source_t) [clone .constprop.55] () from /home/container/bin/engine_srv.so
12 | #5  0xf655f4dd in Cmd_Exec_f(CCommand const&) ()
13 | from /home/container/bin/engine_srv.so
14 | #6  0xeb5e04e9 in __SourceHook_FHCls_ConCommandDispatchfalse::Func(CCommand const&) () from /home/container/tf/addons/metamod/bin/metamod.2.tf2.so
15 | #7  0xf655efe2 in Cmd_ExecuteCommand(CCommand const&, cmd_source_t, int) ()
16 | from /home/container/bin/engine_srv.so
17 | #8  0xf655f0e2 in Cbuf_ExecuteCommand(CCommand const&, cmd_source_t) [clone .constprop.55] () from /home/container/bin/engine_srv.so
18 | #9  0xf655f4dd in Cmd_Exec_f(CCommand const&) ()
19 | from /home/container/bin/engine_srv.so

```
